spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Swallows?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    #本地数据库账号密码
    username: root
    password: 123
  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/static/, file:${web.upload_path}
  #配置文件上传
  servlet:
    multipart:
      #文件上传是否开启
      enabled: true
      #单个数据的大小
      max-file-size: 1Mb
      #总数据的大小
      max-request-size: 10Mb
      #上传文件临时存放位置
      location:

#文件上传路径
web.upload_path: D:\springboot开发\雏雁项目\WeSwallows\src\main\resources\static\images


server:
  port: 8080

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log
